[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run production",
    "php artisan optimize"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"